---
sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1
services: docker
before_install:
  - cd RestWithASP-NET5Udemy-My-Version/RestWithASPNETUdemy/
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME"
    --password-stdin
deploy:
  provider: script
  script: docker tag rest-with-asp-net-udemy:latest
    $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID docker push
    $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
  on:
    brach: main
notifications:
  email: false
