sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5
services: docker
before_install:
  - cd RestWithASP-NET5Udemy-My-Version/RestWithASPNETUdemy
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME"
    --password-stdin
deploy:
  provider: script
  script: docker tag api-asp-net-core-5:latest
    $DOCKER_USERNAME/api-asp-net-core-5:$TRAVIS_JOB_ID; docker push
    $DOCKER_USERNAME/api-asp-net-core-5:$TRAVIS_JOB_ID;
  on:
    brach: main
notifications:
  email: false
